#include "ifma_amd64.h"

DATA ifmaUnit<>+0(SB)/8, $1
DATA ifmaUnit<>+8(SB)/8, $1
DATA ifmaUnit<>+16(SB)/8, $1
DATA ifmaUnit<>+24(SB)/8, $1
#ifndef IFMA_VL
DATA ifmaUnit<>+32(SB)/8, $1
DATA ifmaUnit<>+40(SB)/8, $1
DATA ifmaUnit<>+48(SB)/8, $1
DATA ifmaUnit<>+56(SB)/8, $1
#endif
GLOBL ifmaUnit<>(SB), RODATA|NOPTR, $(5*IFMA_STEP)

TEXT ·ifmaCanonicalFilter(SB), NOSPLIT, $0-24
	MOVQ value+0(FP), AX
	MOVQ plan+8(FP), DI
	MOVQ AX, BX
	LOAD_LEFT
	MOVQ $19, DX
	VPBROADCASTQ DX, Z5
	VPADDQ Z16, Z5, Z6
	VPSRLQ $51, Z6, Z6
	VPADDQ Z17, Z6, Z6
	VPSRLQ $51, Z6, Z6
	VPADDQ Z18, Z6, Z6
	VPSRLQ $51, Z6, Z6
	VPADDQ Z19, Z6, Z6
	VPSRLQ $51, Z6, Z6
	VPADDQ Z20, Z6, Z6
	VPSRLQ $51, Z6, Z6
	VPSLLQ $4, Z6, Z7
	VPADDQ Z6, Z7, Z7
	VPADDQ Z6, Z7, Z7
	VPADDQ Z6, Z7, Z7
	VPADDQ Z16, Z7, Z0
	MOVQ $0x7ffffffffffff, DX
	VPBROADCASTQ DX, Z26
	VPSRLQ $51, Z0, Z6
	VPANDQ Z26, Z0, Z0
	VPADDQ Z17, Z6, Z1
	VPSRLQ $51, Z1, Z6
	VPANDQ Z26, Z1, Z1
	VPADDQ Z18, Z6, Z2
	VPSRLQ $51, Z2, Z6
	VPANDQ Z26, Z2, Z2
	VPADDQ Z19, Z6, Z3
	VPSRLQ $51, Z3, Z6
	VPANDQ Z26, Z3, Z3
	VPADDQ Z20, Z6, Z4
	VPANDQ Z26, Z4, Z4
	STORE
	VPSLLQ $51, Z1, Z5
	VPORQ Z0, Z5, Z5
	MOVQ 128(DI), CX
	XORQ AX, AX
filter_loop:
	VPBROADCASTQ 0(DI), Z6
	VPBROADCASTQ 8(DI), Z7
	VPANDQ Z5, Z6, Z6
	VPCMPQ $0, Z7, Z6, K1
	KMOVW K1, DX
	ORQ DX, AX
	ADDQ $16, DI
	DECQ CX
	JNZ filter_loop
	MOVQ AX, mask+16(FP)
	VZEROUPPER
	RET

TEXT ·ifmaMultiply(SB), NOSPLIT, $0-24
	MOVQ result+0(FP), AX
	MOVQ left+8(FP), BX
	MOVQ right+16(FP), CX
	LOAD_LEFT
	LOAD_RIGHT
	MULTIPLY
	JOIN
	NORMALIZE
	STORE
	VZEROUPPER
	RET

TEXT ·ifmaForward(SB), NOSPLIT, $0-24
	MOVQ centers+0(FP), DI
	MOVQ scratch+8(FP), SI
	MOVQ offset+16(FP), R8
	MOVQ $IFMA_GROUPS, R10
	LEAQ ifmaUnit<>(SB), R9
forward_loop:
	MOVQ SI, AX
	MOVQ DI, BX
	MOVQ R8, CX
	MUL
	LEAQ (5*IFMA_STEP)(SI), AX
	LEAQ (5*IFMA_STEP)(DI), BX
	LEAQ (5*IFMA_STEP)(R8), CX
	MUL
	LEAQ (10*IFMA_STEP)(SI), AX
	LEAQ (10*IFMA_STEP)(DI), BX
	LEAQ (10*IFMA_STEP)(R8), CX
	MUL
	LEAQ (15*IFMA_STEP)(SI), AX
	LEAQ (10*IFMA_STEP)(SI), BX
	LOAD_LEFT
	SQUARE
	JOIN
	NORMALIZE
	STORE
	LEAQ ifmaUnit<>(SB), BX
	MOVQ AX, CX
	LOAD_LEFT
	LOAD_RIGHT
	SUB
	NORMALIZE
	STORE
	MOVQ AX, CX
	MOVQ R9, BX
	LEAQ (20*IFMA_STEP)(SI), AX
	MUL
	MOVQ AX, R9
	ADDQ $(15*IFMA_STEP), DI
	ADDQ $(35*IFMA_STEP), SI
	DECQ R10
	JNZ forward_loop
	VZEROUPPER
	RET

TEXT ·ifmaReverse(SB), NOSPLIT, $0-24
	MOVQ scratch+0(FP), SI
	MOVQ inverse+8(FP), DI
	MOVQ factor+16(FP), R8
	ADDQ $((IFMA_GROUPS-1)*35*IFMA_STEP), SI
	MOVQ $(IFMA_GROUPS-1), R10
reverse_loop:
	LEAQ (25*IFMA_STEP)(SI), AX
	MOVQ DI, BX
	LEAQ (-15*IFMA_STEP)(SI), CX
	MUL
	MOVQ DI, AX
	MOVQ DI, BX
	LEAQ (15*IFMA_STEP)(SI), CX
	MUL
	JMP reverse_factor
reverse_first:
	MOVQ DI, BX
	LEAQ (25*IFMA_STEP)(SI), AX
	LOAD_LEFT
	VMOVDQU64 Z16, 0(AX)
	VMOVDQU64 Z17, IFMA_STEP(AX)
	VMOVDQU64 Z18, (2*IFMA_STEP)(AX)
	VMOVDQU64 Z19, (3*IFMA_STEP)(AX)
	VMOVDQU64 Z20, (4*IFMA_STEP)(AX)
reverse_factor:
	MOVQ R8, AX
	LEAQ (25*IFMA_STEP)(SI), BX
	LEAQ (10*IFMA_STEP)(SI), CX
	MUL
	LEAQ (30*IFMA_STEP)(SI), AX
	LEAQ (25*IFMA_STEP)(SI), BX
	MOVQ R8, CX
	LOAD_LEFT
	LOAD_RIGHT
	SUB
	NORMALIZE
	STORE
	LEAQ (25*IFMA_STEP)(SI), AX
	LOAD_LEFT
	LOAD_RIGHT
	ADD
	NORMALIZE
	STORE
	TESTQ R10, R10
	JZ reverse_done
	SUBQ $(35*IFMA_STEP), SI
	DECQ R10
	JZ reverse_first
	JMP reverse_loop
reverse_done:
	VZEROUPPER
	RET

TEXT ·ifmaSquare(SB), NOSPLIT, $0-16
	MOVQ result+0(FP), AX
	MOVQ source+8(FP), BX
	LOAD_LEFT
	SQUARE
	JOIN
	NORMALIZE
	STORE
	VZEROUPPER
	RET

TEXT ·ifmaAdd(SB), NOSPLIT, $0-24
	MOVQ result+0(FP), AX
	MOVQ left+8(FP), BX
	MOVQ right+16(FP), CX
	LOAD_LEFT
	LOAD_RIGHT
	VPADDQ Z16, Z21, Z0
	VPADDQ Z17, Z22, Z1
	VPADDQ Z18, Z23, Z2
	VPADDQ Z19, Z24, Z3
	VPADDQ Z20, Z25, Z4
	NORMALIZE
	STORE
	VZEROUPPER
	RET

TEXT ·ifmaSubtract(SB), NOSPLIT, $0-24
	MOVQ result+0(FP), AX
	MOVQ left+8(FP), BX
	MOVQ right+16(FP), CX
	LOAD_LEFT
	LOAD_RIGHT
	MOVQ $0xfffffffffffda, DX
	VPBROADCASTQ DX, Z27
	VPADDQ Z27, Z16, Z0
	MOVQ $0xffffffffffffe, DX
	VPBROADCASTQ DX, Z27
	VPADDQ Z27, Z17, Z1
	VPADDQ Z27, Z18, Z2
	VPADDQ Z27, Z19, Z3
	VPADDQ Z27, Z20, Z4
	VPSUBQ Z21, Z0, Z0
	VPSUBQ Z22, Z1, Z1
	VPSUBQ Z23, Z2, Z2
	VPSUBQ Z24, Z3, Z3
	VPSUBQ Z25, Z4, Z4
	NORMALIZE
	STORE
	VZEROUPPER
	RET
